"use client";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { useRouter } from 'next/navigation';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const TopBarNav = () => {
  const router = useRouter();
  return (
    <div className="w-full h-12 bg-neutral-900 flex items-center justify-between px-4">
      <div className="text-white font-medium">Table Quote Presenter</div>
      <div className="flex items-center gap-4">
        <button
          className="text-white"
          onClick={() => router.push('/')}
        >
          Home
        </button>
        <button
          className="text-white"
          onClick={() => router.push('/display/default')}
        >
          Default Stage
        </button>
      </div>
    </div>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-screen flex flex-col antialiased`}>
        <TopBarNav />
        <div className="flex-grow overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
