"use client";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Structure from './structure.js';
import TitleBar from '@/components/TitleBar';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="max-h-screen overflow-hidden">
      <body className="h-screen overflow-hidden">
        <div className="h-screen overflow-hidden flex flex-col">
          <TitleBar />
          <div className="flex-1 overflow-hidden">
            <Structure hideNav>{children}</Structure>
          </div>
        </div>
      </body>
    </html>
  );
}
